### ISSUE TITLE
it is necessary to put a check in Search() for boundary values

### ISSUE THREAD

**Issue by NovikovRoman** [algerbrex/blunder#17]
engine/search.go

```go
func (search *Search) Search() Move {
…
    if score <= alpha || score >= beta {
        alpha = -Inf
        beta = Inf
        depth--
        
        // important check -----------------------------------------------
        if depth == 0 {
            break
        }
        // important check -----------------------------------------------

        continue
    }
…
}
```

**Comment by algerbrex** [comment]
Hi, thanks for these bug reports @NovikovRoman They're much appreciated. I should have time soon to take a good look over them and the code to be able to see if they might be an issue.

**Comment by algerbrex** [comment]
After considering this issue, I don't believe the check for depth == 1 is needed, since the score will never be outside of the alpha and beta bounds at a depth of 1. The only way this could occur from my estimation is if Blunder was given a position where checkmate was already delivered. But such a position will never be given to Blunder by any chess GUI or chess match handler, and if the user passes in such a position, it makes sense Blunder would crash. Nevertheless, it might be more aesthetic to handle such cases gracefully, so I'll look into that.

**Comment by NovikovRoman** [comment]
I also think that it is better to consider all possible options.
