### ISSUE TITLE
Blunder v8.0.0 underestimates danger ?

### ISSUE THREAD

**Issue by tissatussa** [algerbrex/blunder#20]
after i successfully compiled your v8.0.0 source code on Linux, i let the avx2 binary play a game against Prophet v4.2 (rating about 2400) .. Blunder lost that game due to a blunder in this position :
(i had to install GO v1.18 manually because my Xubuntu 21.10 has v1.17)

`r1bq2k1/pp3rpp/2p2b2/3p4/1B6/1R1B3P/P1P2PP1/3QR1K1 b - - 0 20`

![blunder_b6](https://user-images.githubusercontent.com/1109281/176646122-20f8bc27-a1c0-4840-88d2-25b55f1874f9.png)

after 35 seconds Blunder played 20...b6 ?? (at depth 16) which underestimates the danger 21.Qh5!
as soon as the game ended i let Blunder examine this position at higher depth .. indeed, then it finds 20...g6 is much better, but it takes a long time to discover this ..

here's the game .. the LiChess link shows a page with engine analysis by a modern StockFish version, which clearly indicates why 21.Qh5! is very strong .. but its line is not depth 16, so i wonder why Blunder doesn't see this continuation .. however, for a human player rated 1800+ this is obvious ?

[Event "engine vs engine"]
[Site "@ [https://lichess.org/TCmrtIqc](https://lichess.org/TCmrtIqc) "]
[Date "2022.06.30"]
[White "Prophet v4.2"]
[Black "Blunder v8.0.0"]
[Result "1-0"]
[ECO "C67"]
[GameDuration "00:48:21"]
[Opening "Ruy Lopez"]
[PlyCount "133"]
[TimeControl "900+10"]
[Variation "Berlin defense, Open Variation"]

`1. e4 {+0.20/14 38s} e5 {-0.23/19 28s} 2. Nf3 {+0.34/14 31s} Nc6 {-0.10/20 29s} 3. Bb5 {+0.30/14 28s} Nf6 {-0.30/17 30s} 4. O-O {+0.29/15 44s} Nxe4 {-0.09/19 31s} 5. d4 {+0.54/14 42s} exd4 {-0.16/20 41s} 6. Re1 {+0.50/14 32s} f5 {-0.16/21 33s} 7. Nbd2 {+0.55/14 40s} Be7 {-0.06/21 34s} 8. Nxe4 {+0.26/14 39s} fxe4 {-0.16/21 35s} 9. Rxe4 {+0.28/14 21s} O-O {-0.16/20 37s} 10. Nxd4 {+0.31/13 19s} Nxd4 {0.00/20 50s} 11. Qxd4 {+0.10/14 19s} d5 {+0.01/20 40s} 12. Re1 {-0.01/14 31s} Bf6 {+0.05/20 42s} 13. Qd1 {-0.02/14 36s} c6 {0.00/23 59s} 14. Bd3 {+0.16/15 22s} Qb6 {0.00/23 47s} 15. Be3 {+0.16/14 22s} Qxb2 {+0.03/24 64s} 16. Rb1 {+0.12/13 18s} Qc3 {0.00/24 58s} 17. Rb3 {+0.21/13 21s} Qa5 {+0.25/20 52s} 18. Bd2 {+0.33/12 33s} Qd8 {+0.34/19 49s} 19. Bb4 {0.00/12 32s} Rf7 {+0.51/17 42s} 20. h3 {-0.13/12 31s} b6 {+0.70/16 35s} 21. Qh5 {+1.18/12 26s} g6 {-1.70/25 35s} 22. Bxg6 {+2.24/18 30s} hxg6 {-1.78/25 30s} 23. Qxg6+ {+2.24/16 29s} Bg7 {-1.73/24 29s} 24. Rf3 {+2.03/14 28s} Bf5 {-1.84/24 27s} 25. Rxf5 {+2.03/15 16s} Rxf5 {-1.76/23 25s} 26. Qxf5 {+2.03/13 27s} Qf6 {-1.81/22 23s} 27. Qxf6 {+2.06/14 27s} Bxf6 {-1.43/23 22s} 28. Re6 {+1.87/17 19s} c5 {-1.36/23 21s} 29. Rxf6 {+1.91/16 21s} cxb4 {-1.36/21 20s} 30. Rc6 {+1.83/16 25s} a5 {-1.54/20 19s} 31. g3 {+1.79/15 24s} Re8 {-1.18/20 18s} 32. Kf1 {+1.76/16 23s} Re4 {-0.71/21 15s} 33. Rxb6 {+1.61/15 12s} a4 {-0.84/21 16s} 34. Rb5 {+1.40/15 21s} Rc4 {-1.07/25 20s} 35. Rxd5 {+1.73/17 23s} Rxc2 {-1.42/24 15s} 36. Rb5 {+1.73/15 22s} b3 {-1.38/18 12s} 37. axb3 {+3.31/20 13s} a3 {-2.79/26 12s} 38. Ra5 {+3.36/19 22s} a2 {-2.97/25 11s} 39. Kg2 {+3.46/18 21s} Kf7 {-3.22/24 11s} 40. Ra7+ {+3.37/17 21s} Ke6 {-3.03/25 11s} 41. h4 {+3.52/17 17s} Kd5 {-3.16/24 11s} 42. h5 {+3.35/16 12s} Kc6 {-3.60/22 11s} 43. h6 {+3.56/16 10s} Kb6 {-3.88/28 14s} 44. h7 {+3.40/17 12s} Rc8 {-4.25/28 17s} 45. Rxa2 {+3.40/15 20s} Rh8 {-4.26/24 9.4s} 46. f4 {+3.69/17 11s} Rxh7 {-5.59/27 9.4s} 47. f5 {+3.72/16 19s} Kc6 {-5.59/25 9.5s} 48. g4 {+3.70/16 19s} Rg7 {-4.10/21 13s} 49. Ra4 {+3.77/16 19s} Rb7 {-4.38/22 12s} 50. f6 {+3.83/15 18s} Kd7 {-4.87/21 9.0s} 51. Rf4 {+3.87/16 18s} Ke8 {-6.15/26 9.2s} 52. b4 {+4.45/18 18s} Kf7 {-5.85/29 9.1s} 53. g5 {+5.23/19 9.9s} Rb8 {-5.85/27 9.2s} 54. Kf3 {+5.23/17 17s} Rb7 {-6.03/24 9.3s} 55. Kg3 {+6.74/17 9.9s} Rb8 {-9.73/23 9.4s} 56. b5 {+7.31/19 14s} Rxb5 {-5.36/29 9.5s} 57. g6+ {+7.31/17 17s} Kxg6 {-6.10/28 10s} 58. f7 {+7.55/20 8.8s} Rg5+ {-M20/21 9.5s} 59. Kf3 {+12.65/13 17s} Rf5 {-M16/22 9.6s} 60. Rxf5 {+13.00/14 17s} Kxf5 {-M14/24 9.6s} 61. f8=Q+ {+13.05/13 16s} Ke6 {-M12/22 9.8s} 62. Ke4 {+327.56/12 16s} Kd7 {-M10/25 13s} 63. Kd5 {+327.58/10 16s} Kc7 {-M8/26 12s} 64. Qa8 {+327.60/8 0.14s} Kd7 {-M6/25 9.1s} 65. Qb7+ {+327.62/5 0.008s} Ke8 {-M4/26 12s} 66. Ke6 {+327.64/3 0.001s} Kd8 {-M2/28 12s} 67. Qd7# {+327.66/1 0s, White mates} 1-0`

**Comment by algerbrex** [comment]
Hi, @tissatussa thanks for the report.

Running the position myself, Blunder 8.0.0, with a fresh start, finds g6 instantly, but erroneously switches to b6 at depth 18. I think this is likely due to a new pruning technique I added in Blunder known as razoring, which you may be familiar with. Removing the razoring code and researching the position, Blunder finds g6 instantly and sticks with it.

So Blunder blundering here was likely caused by some faulty razoring, which made it blind to the force of Qh5. Trying to tune your search parameters well is a million-dollar question, and in hyper-bullet testing over about 4500 games, razoring proved to be a net win, but in positions like the one you showed, it's likely too aggressive I'll need to work on tuning it down for the next release of Blunder.

**Comment by mkd** [comment]
Hi, and sorry for getting in the middle of the conversation, but:

I just noticed that, in your moves loop you have a very aggressive
condition where any move with SEE<0 will be immediately pruned. Here's the
link to the code in search.go:
https://github.com/algerbrex/blunder/blob/527906ccccdb0c603dc62e9ea1a885c0c7c333f3/engine/search.go#L637

I tried that pruning condition on my own engine and it starts making huge
blunders when there's a potential threat or mate, and it actually depends
on a negative capture. If you try removing that condition, the engine (also
Blunder 8.0) starts playing so much better.

Regards,
--Claudio


--
Claudio M. Camacho
Strategic Marketing Management // Business Strategy & Leadership //
Executive Board Advisor

tel: +358 (0) 50 3555 638
web: www.claudiocamacho.io
twitter: twitter.com/claudiomkd
linkedin: http://www.linkedin.com/in/claudiocamacho
medium: ***@***.***

**Comment by algerbrex** [comment]
Hi @mkd thanks for the heads up.

You're correct. In *quiesecene* search, I am pruning all moves that have an SEE score of 0. As I mentioned to tissatusa, the hope is that the blindness that comes with doing such an approach is minimal, and mostly out weighed by the strength gained by being able to search good lines deeper on average. And if I remember correctly from my hyperbullet testing, SEE pruning proved to be an overall win.

You mentioned Blunder started playing much better after SEE was removed. Did you mean you also did some testing to determine the Elo gain/loss from removing SEE pruning from Blunder? Could you share those results? Thanks!

**Comment by mkd** [comment]
Hi Christian,

No, I haven't done any proper testing. I just happened to implement my own
SEE and got a lot of ideas from Blunder's code, because you have a nice and
clean implementation (in my opinion). Then, I checked where do you use
SEE() for pruning and, within qsearch it's completely fine. However, when I
tried to prune also in the general search, at the beginning of the "moves
loop", my engine started to miss out on tactical positions where there were
deep threats.

I read the message from Roelof and tried the same position:
r1bq2k1/pp3rpp/2p2b2/3p4/1B6/1R1B3P/P1P2PP1/3QR1K1 b - - 0 20

After that, I realized having SEE() as a pruning decision in the general
search is too harsh and will miss out on positions where there are
long-term deep threats that are not imminent.

I didn't do anything else than that. But feel free to try removing SEE()
from your moves loop in the general search, and see what happens. I also
tested my own engine and the amount of nodes saved, in my case, is almost
neglectible. So having SEE() pruning or not in the general search doesn't
help my engine at all. Therefore, I only kept it in the qsearch.


Hope this explanation helps you a bit more. By the way, thank you for
writing Blunder, I've learned a lot from your code and introduced a few
ideas into my own engine, adapting them to C++ code.


Keep up the great work!


--
Claudio M. Camacho
Strategic Marketing Management // Business Strategy & Leadership //
Executive Board Advisor

tel: +358 (0) 50 3555 638
web: www.claudiocamacho.io
twitter: twitter.com/claudiomkd
linkedin: http://www.linkedin.com/in/claudiocamacho
medium: ***@***.***
